### ISSUE TITLE
EntityReader GetByPage

### ISSUE THREAD

**Issue by ArsenioInojosa** [GenesysSource/Framework#2]
Hello,

![image](https://user-images.githubusercontent.com/11929923/48559189-7c819780-e8c1-11e8-9ba3-3273cd599fcc.png)

`queryable = pageNumber <= 0 || pageSize <= 0 ? source3 : source3.Skip<TEntity>(pageNumber * pageSize).Take<TEntity>(pageSize).AsQueryable<TEntity>();`

Assume a list of 10 elements. pageNumber = 1 and pageSize = 5

`queryable = source3.Skip<TEntity>(1 * 5).Take<TEntity>(5).AsQueryable<TEntity>();`

The Skip (1 * 5) is performed and the first 5 records are never displayed.

Consider changing to:

`queryable = pageNumber <= 0 || pageSize <= 0 ? source3 : source3.Skip<TEntity>((pageNumber - 1) * pageSize).Take<TEntity>(pageSize).AsQueryable<TEntity>();`

Thank

**Comment by goodtocode** [comment]
Hi @ArsenioInojosa,
Thanks for the great find. This will be fixed in the current iteration, on the next commit. 
Feel free to share any other thoughts or findings, always happy to work with our peers in the community.
Thanks again!
Robert

**Comment by goodtocode** [comment]
Hi @ArsenioInojosa,
This issue has been fixed and committed to the main branch. 
Thank you again for your help, very much appreciated!
Robert
